build: false
shallow_clone: true

environment:
  ELECTRON_NO_ATTACH_CONSOLE: 1
  VSCODE_BUILD_VERBOSE: true

  matrix:
    # - CODE_VERSION: "1.20.0" # Minimal Version
    - CODE_VERSION: "*" # Last Stable Version
    # - CODE_VERSION: "insiders" # Insider Version

cache:
  - node_modules
  - '%APPDATA%\npm-cache\_cacache\index-v5' # Only indexes

install:
  - node --version
  - npm --version
  - npm install --no-audit
  - npm install mocha-appveyor-reporter

before_test:
  - npm run vscode:prepublish

test_script:
  - npm test --silent
