build: false
shallow_clone: true

environment:
  ELECTRON_NO_ATTACH_CONSOLE: 1
  VSCODE_BUILD_VERBOSE: true
  COVERALLS_PARALLEL: true

  matrix:
    # - CODE_VERSION: "1.20.0" # Minimal Version
    - CODE_VERSION: "*" # Last Stable Version
    # - CODE_VERSION: "insiders" # Insider Version

cache:
  - node_modules
  - '%APPDATA%\npm-cache\_cacache\index-v5' # Only indexes

install:
  - node --version
  - npm --version
  - npm install --no-audit

before_test:
  - npm run vscode:prepublish
  # Enable coverage for `extension.ts`
  - ps: (get-content package.json) | %{$_ -replace '"\*"',''} | set-content package.json

test_script:
  - npm test --silent

on_finish:
  # Update the test list on AppVeyor
  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path 'test-reports\extension_tests.xml'))

  # Update coverage
  - type coverage\lcov.info | node_modules\.bin\coveralls