git:
  commitMessage: "chore(release): v${version}"
  tagAnnotation: "chore(release): v${version}"
  tagName: "v${version}"

hooks:
  after:bump: 
    - "npm run changelog:update"
    - "npm run organize"

plugins:
  "@release-it/conventional-changelog":
    preset: "angular"
    outputUnreleased: true
    releaseCount: 1

npm:
  publish: false
  private: true
  registry: "OMITTED"
