language: node_js

node_js: 8

os:
  - linux
  - osx

env:
  global:
    - MOCHA_COLORS=1 # Force Mocha Colors
  matrix:
    - CODE_VERSION=1.22.0 # Minimal Version
    - CODE_VERSION= # Last Stable Version
    - CODE_VERSION=insiders # Insider Version

cache:
  directories:
    - "node_modules"

addons:
  apt:
    packages:
    - libgconf-2-4
    - libsecret-1-dev
    - xvfb

install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
  - node --version
  - npm --version
  - travis_retry npm install

before_script:
  - npm run vscode:prepublish
  # Enable coverage for `extension.ts`
  - sed -i.bak 's/"\*"//g' package.json

script:
  - npm run lint
  - travis_retry npm test -- --download-only
  - npm test --silent

after_script:
  - node_modules/.bin/codecov --disable=gcov